version: 2

models:
  - name: stg_activities
    description: "Staging model for raw_activities data"
    columns:
      - name: activity_id
        tests:
          - not_null
          - unique

      - name: patient_id
        tests:
          - not_null

      - name: activity_date
        tests:
          - not_null

      - name: activity_type
        tests:
          - not_null
  - name: stg_patients
    description: "Staging model for raw_patients data"
    columns:
      - name: patient_id
        tests:
          - not_null

      - name: practice_id
        tests:
          - not_null

      - name: age
        tests:
          - not_null

      - name: registration_date
        tests:
          - not_null

      - name: email
        tests:
          - not_null

      - name: phone
        tests:
          - not_null
    tests:
    - dbt_utils.unique_combination_of_columns:
        combination_of_columns:
          - patient_id
          - practice_id
 